default:
  before_script:
    - bash ci/docker_install.sh > /dev/null
    - bash ci/setup_php.sh > /dev/null

composer:
  stage: build
  inherit:
    default: false
  artifacts:
    untracked: true
  image: composer
  script:
    - composer install

test:8.1:
  stage: test
  dependencies:
    - composer
  image: php:8.1
  variables:
    XDEBUG_MODE: coverage
  script:
    - phpunit --configuration phpunit.xml
  artifacts:
    paths:
      - build/coverage/
