variables:
  DEBCONF_NOWARNINGS: "yes"

default:
  before_script:
    - bash build/ci/docker_install.sh > /dev/null
    - bash build/ci/setup_php.sh > /dev/null

composer:
  stage: build
  inherit:
    default: false
  artifacts:
    untracked: true
  image: composer
  script:
    - composer install

test:8.1:
  stage: test
  dependencies:
    - composer
  image: php:8.1
  variables:
    XDEBUG_MODE: coverage
  script:
    - vendor/bin/phpunit --configuration phpunit.xml
  artifacts:
    paths:
      - build/coverage/
