version: '3'

services:
  httpd:
    build:
      context: httpd
      args:
        - HTTPD_VERSION=${HTTPD_VERSION}
    ports:
      - "80:80"
  php:
    build:
      context: php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - type: bind
        source: ./htdocs
        target: /usr/local/apache2/htdocs
