version: '3'

services:
  httpd:
    build:
      context: httpd
      args:
        - HTTPD_VERSION=${HTTPD_VERSION}
    volumes:
      - type: bind
        source: ./htdocs
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ../..
        target: /usr/local/apache2/${APP_NAME}
    environment:
      - APP_NAME
      - APP_HOST
    ports:
      - "80:80"
  php:
    build:
      context: php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_BIN_DIR=/usr/local/apache2/${APP_NAME}/vendor/bin
    volumes:
      - type: bind
        source: ./htdocs
        target: /usr/local/apache2/htdocs
      - type: bind
        source: ../..
        target: /usr/local/apache2/${APP_NAME}
    working_dir: /usr/local/apache2/${APP_NAME}
  db:
    build:
      context: postgres
      args:
        - VERSION=${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
