version: '3'

services:
  httpd:
    volumes:
      - type: bind
        source: ../..
        target: /usr/local/apache2/${APP_NAME}
    environment:
      - APP_NAME
      - APP_HOST
  php:
    volumes:
      - type: bind
        source: ../..
        target: /usr/local/apache2/${APP_NAME}
    working_dir: /usr/local/apache2/${APP_NAME}
